name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  # deployment and tag_release steps removed temporarily
  check_commit_message:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Print Commit(s)
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: Print Commit(s) Message
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Check Commit Messages
        run: |
          commit_messages=$(git log --format=%B -n 1 ${{ github.sha }})
          if contains(join(',', ${{ toJson(github.event.commits.*.message) }}), '#skip'); then
            echo "Commit contains '#skip'. Skipping deployment and tagging."
            exit 0
          else
            echo "Commit does not contain '#skip'. Proceeding with deployment and tagging."
            # Add your deployment and tagging steps here
          fi
